name: Guestbook workflow

on:
  issues:
    types: [opened, closed, reopened, deleted, edited]

jobs:
  update_guestbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Update guestbook
        uses: muety/readme-guestbook@v1.0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_entries: 10